CLUSTAL multiple sequence alignment by MUSCLE (3.8)


Certhidea_olivacea            ------------GGATCCCTGTTAGGAGTTTGCTTAATCACTCAAATCGTCACAGGTCTC
Certhidea_fusca               TGATGAAACTTCGGATCCCTGTTAGGAGTTTGCTTAATCACTCAAATCGTCACAGGTCTC
Pinaroloxias_inornata         ------------GGATCCCTGTTAGGAGTTTGCTTAATCACTCAAATCGTCACAGGTCTC
Platyspiza_crassirostris      ------------GGATCCCTGTTAGGAGTTTGCTTAATCACCCAAATCATCACAGGTCTC
Cactospiza_heliobates         ---------------------------------TTAATCACTCAAATCNTCACAGGTCTC
Camarhynchus_pauper           ------------GGATCCCTGTTAGGAGTTTGCTTAATCACTCAAATCATCACAGGTCTC
Geospiza_difficilis           ------------GGATCCCTGTTAGGAGTTTGCTTAATCACTCAAATCATCACAGGTCTC
Geospiza_fuliginosa           ------------GGATCCCTGTTAGGAGTTTGCTTAATCACTCAAATCATCACAGGTCTC
Geospiza_fortis               ------------GGATCCCTGTTAGGAGTTTGCTTAATCACTCAAATCATTACAGGTCTC
Geospiza_conirostris          ------------GGATCCCTGTTAGGAGTTTGCTTAATCACTCAAATCATCACAGGTCTC
Geospiza_magnirostris         ------------GGATCCCTGTTAGGAGTTTGCTTAATCACTCAAATCATCACAGGTCTC
Geospiza_scandens             ------------GGATCCCTGTTAGGAGTTTGCTTAATCACTCAAATCATCACAGGTCTC
Camarhynchus_psittacula       ------------GGATCCCTGTTAGGAGTTTGCTTAATCACTCAAATCATCACAGGTCTC
Cactospiza_pallida            ------------GGATCCCTGTTAGGAGTTTGCTTAATCACTCAAATCATCACAGGTCTC
Camarhynchus_parvulus         ------------GGATCCCTGTTAGGAGTTTGCTTAATCACTCAAATCATCACAGGTCTC
                                                               ******** ****** * *********

Certhidea_olivacea            CTTCTAGCCATGCACTACACAGCAGACACCAACCTAGCCTTCTCCTCCGTCGCCCACATA
Certhidea_fusca               CTTCTAGCCATGCACTACACAGCAGACACCAACCTAGCCTTCTCCTCCGTCGCCCACATA
Pinaroloxias_inornata         CTTCTAGCCATACACTACACAGCAGACACCAACCTAGCCTTCTCCTCCGTCGCCCACATA
Platyspiza_crassirostris      CTTCTAGCCATGCACTACACAGCAGACACCGACCTAGCCTTCTCCTCCGTCGCCCACATA
Cactospiza_heliobates         CTTCTAGCCATACACTACACAGCAGACACCAACCTAGCCTTCTCCTCCGTCGCCCACATA
Camarhynchus_pauper           CTTCTAGCCATACACTACACAGCAGACACCAACCTAGCCTTCTCCTCCGTCGCCCACATA
Geospiza_difficilis           CTTCTAGCCATGCACTACACAGCAGACACCAACCTAGCCTTCTCCTCCGCCGCCCACATA
Geospiza_fuliginosa           CTTCTAGCCATGCACTACACAGCAGACACCAACCTAGCCTTTTCCTCCGTCGCCCACATA
Geospiza_fortis               CTTCTAGCCATGCACTACACAGCAGACACCAACCTAGCCTTCTCCTCCGTCGCCCACATA
Geospiza_conirostris          CTTCTAGCCATGCACTACACAGCAGACACCAACCTAGCCTTCTCCTCCGTCGCCCACATA
Geospiza_magnirostris         CTTCTAGCCATGCACTACACAGCAGACACCAACCTAGCCTTCTCCTCCGTCGCCCACATA
Geospiza_scandens             CTTCTAGCCATGCACTACACAGCAGACACCAACCTAGCCTTCTCCTCCGTCGCCCACATA
Camarhynchus_psittacula       CTTCTAGCCATACACTACACAGCAGACACCAACCTAGCCTTCTCCTCCGTCGCCCACATA
Cactospiza_pallida            CTTCTAGCCATACACTACACAGCAGACACCAACCTAGCCTTCTCCTCCGTCGCCCACATA
Camarhynchus_parvulus         CTTCTAGCCATACACTACACAGCAGACACCAACCTAGCCTTCTCCTCCGTCGCCCACATA
                              *********** ****************** ********** ******* **********

Certhidea_olivacea            TGCCGAGACGTCCAATTCGGCTGACTCATCCGCAACCTCCACGCAAACGGAGCCTCCTTC
Certhidea_fusca               TGCCGAGACGTCCAATTCGGCTGACTCATCCGCAACCTCCACGCAAACGGAGCCTCCTTC
Pinaroloxias_inornata         TGCCGAGACGTCCAATTCGGCTGACTTATCCGCAACCTCCACGCAAACGGAGCCTCCTTC
Platyspiza_crassirostris      TGCCGAGACGTCCAATTCGGCTGACTCATCCGCAACCTTCACGCAAACGGAGCCTCTTTC
Cactospiza_heliobates         TGCCGAGACGTCCAATTCGGCTGACTCATCCGCAACCTCCATGCAAACGGAGCCTCCTTC
Camarhynchus_pauper           TGCCGAGACGTCCAATTCGGCTGACTCATCCGCAACCTCCACGCAAACGGGGCCTCCTTC
Geospiza_difficilis           TGCCGAGACGTNCAATTCGGCTGACTCATCCGCAACCTCCATGCAAACGGAGCCTCCTTC
Geospiza_fuliginosa           TGCCGAGACGTCCAATTCGGCTGACTCATCCGCAACCTCCATGCAAACGGAGCCTCCTTC
Geospiza_fortis               TGCCGAGACGTCCAATTCGGCTGACTCATCCGCAACCTCCATGCAAACGGAGCCTCCTTC
Geospiza_conirostris          TGCCGAGACGTCCAATTCGGCTGACTCATCCGCAACCTCCATGCAAACGGAGCCTCCTTC
Geospiza_magnirostris         TGCCGAGACGTCCAATTCGGCTGACTCATCCGCAACCTCCATGCAAACGGAGCCTCCTTC
Geospiza_scandens             TGCCGAGACGTCCAATTCGGCTGACTCATCCGCAACCTCCATGCAAACGGAGCCTCCTTC
Camarhynchus_psittacula       TGCCGAGACGTCCAATTCGGCTGACTCATCCGCAACCTCCACGCAAACGGAGCCTCCTTC
Cactospiza_pallida            TGCCGAGACGTCCAATTCGGCTGACTCATCCGCAACCTCCACGCAAACGGAGCCTCCTTC
Camarhynchus_parvulus         TGCCGAGACGTCCAATTCGGCTGACTCATCCGCAACCTCCACGCAAACGGAGCCTCCTTC
                              *********** ************** *********** ** ******** ***** ***

Certhidea_olivacea            TTCTTCATCTGCATCTACCTACACATCGGACGAGGTATCTACTACGGCTCATACCTAAAT
Certhidea_fusca               TTCTTCATCTGCATCTACCTACACATCGGACGAGGTATCTACTACGGCTCATACCTAAAT
Pinaroloxias_inornata         TTCTTCATCTGCATCTACCTACACATCGGACGAGGAATCTACTACGGCTCATACCTAAAC
Platyspiza_crassirostris      TTCTTCATCTGCATCTACCTACACATCGGACGAGGAATCTACTACGGCTCATACCTAAAT
Cactospiza_heliobates         TTCTTCATCTGCATCTACCTACACATCGGNCGAGGAATCTACTACGGCTNATACCTAAAT
Camarhynchus_pauper           TTCTTCATCTGCATCTACCTACACATCGGACGAGGAATCTACTACGGCTCATACCTAAAT
Geospiza_difficilis           TTCTTCATCTGCATCTACCTACACATCGGACGAGGAATCTACTACGGCTCATACCTAAAT
Geospiza_fuliginosa           TTCTTCATCTGCATCTACCTACACATCGGACGAGGAATCTACTACGGCTCATACCTAAAT
Geospiza_fortis               TTCTTCATCTGCATCTACCTACACATCGGACGAGGAATCTACTACGGCTCATGCCTAAAT
Geospiza_conirostris          TTCTTCATCTGCATCTACCTACACATCGGACGAGGAATCTACTACGGCTCATACCTAAAT
Geospiza_magnirostris         TTCTTCATCTGCATCTACCTACACATCGGACGAGGAATCTACTACGGCTCATACCTAAAT
Geospiza_scandens             TTCTTCATCTGCATCTACCTACACATCGGACGAGGAATCTACTACGGCTCATACCTAAAT
Camarhynchus_psittacula       TTCTTCATCTGCATCTACCTACACATCGGACGAGGAATCTACTACGGCTCATACCTAAAT
Cactospiza_pallida            TTCTTCATCTGCATCTACCTACACATCGGACGAGGAATCTACTACGGCTCATACCTAAAT
Camarhynchus_parvulus         TTCTTCATCTGCATCTACCTACACATCGGACGAGGAATCTACTACGGCTCATACCTAAAT
                              ***************************** ***** ************* ** ****** 

Certhidea_olivacea            AAAGAAACCTGAAACATTGGAGTCATCCTCCTCCTAACCCTCATAGCAACAGCCTTCGTA
Certhidea_fusca               AAAGAAACCTGAAACATTGGAGTCATCCTCCTCCTAACCCTCATAGCAACAGCCTTCGTA
Pinaroloxias_inornata         AAAGAAACCTGAAACATTGGAGTCATCCTCCTCCTAACCCTCATAGCAACAGCCTTTGTA
Platyspiza_crassirostris      AAAGAAACCTGAAACATTGGAGTCATCCTCCTCCTGACCCTCATAGCAACAGCCTTTGTA
Cactospiza_heliobates         AAAGAAACCTGAAACATTGGAGTCATCCTCCTCCTAACCCTCATAGCAACAGCCTTTGTA
Camarhynchus_pauper           AAAGAAACCCGAAACATTGGAGTCATCCTCCTCCTAACCCTCATAGCAACAGCCTTTGTA
Geospiza_difficilis           AAAGAAACCTGAAACATTGGAGTCATCCTCCTCCTAACCCTCATAGCAACAGCCTTTGTA
Geospiza_fuliginosa           AAAGAAACCTGAAACATTGGAGTCATCCTCCTCCTAACCCTCATAGCAACAGCCTTTGTA
Geospiza_fortis               AAAGAAACCTGAAACATTGGAGTCATCCTCCTCCTAACCCTCATAGCAACAGCCTTTGTA
Geospiza_conirostris          AAAGAAACCTGAAACATTGGAGTCATCCTCCTCCTAACCCTCATAGCAACAGCCTTTGTA
Geospiza_magnirostris         AAAGAAACCTGAAACATTGGAGTCATCCTCCTCCTAACCCTCATAGCAACAGCCTTTGTA
Geospiza_scandens             AAAGAAACCTGAAACATTGGAGTCATCCTCCTCCTAACCCTCATAGCAACAGCCTTTGTA
Camarhynchus_psittacula       AAAGAAACCTGAAACATTGGAGTCATCCTCCTCCTAACCCTCATAGCAACAGCCTTTGTA
Cactospiza_pallida            AAAGAAACCTGAAACATTGGAGTCATCCTCCTCCTAGCCCTCATAGCAACAGCCTTTGTA
Camarhynchus_parvulus         AAAGAAACCTGAAACATTGGAGTCATCCTCCTCCTAACCCTCATAGCAACAGCCTTTGTA
                              ********* *************************  ******************* ***

Certhidea_olivacea            GGATACGTCCTACCATGAGGCCAAATATCCTTCTGAGGGGCTACCGTAATCACAAACCTG
Certhidea_fusca               GGATACGTCCTACCATGAGGCCAAATATCCTTCTGAGGGGCTACCGTAATCACAAACCTG
Pinaroloxias_inornata         GGATACGTCCTACCATGAGGCCAAATATCCTTCTGAGGAGCTACCGTAATCACAAACCTA
Platyspiza_crassirostris      GGATACGTCCTACCATGAGGCCAAATATCCTTCTGAGGGGCTACCGTAATCACAAACCTA
Cactospiza_heliobates         GGATACGTCCTACCATGAGGCCAAATATCCTTCTGAGGAGCTACCGTAATCACAAACCTA
Camarhynchus_pauper           GGATACGTCCTACCATGAGGCCAAATATCCTTCTGAGGAGCTACCGTAATCACAAACCTA
Geospiza_difficilis           GGATACGTCCTACCATGAGGCCAAATATCCTTCTGAGGAGCTACCGTAATCACAAACCTA
Geospiza_fuliginosa           GGATACGTCCTACCATGAGGCCAAATATCCTTCTGAGGAGCTACCGTAATCACAAACCTA
Geospiza_fortis               GGGTACGTCCTACCATGAGGCCAAATATCCTTCTGAGGAGCTACCGTAATCACAAACCTA
Geospiza_conirostris          GGATACGTCCTACCATGAGGCCAAATATCCTTCTGAGGAGCTACCGTAATCACAAACCTA
Geospiza_magnirostris         GGATACGTCCTACCATGAGGCCAAATATCCTTCTGAGGAGCTACCGTAATCACAAACCTA
Geospiza_scandens             GGATACGTCCTACCATGAGGCCAAATATCCTTCTGAGGAGCTACCGTAATCACAAACCTA
Camarhynchus_psittacula       GGATACGTCCTACCATGAGGCCAAATATCCTTCTGAGGAGCTACCGTAATCACAAACCTA
Cactospiza_pallida            GGATACGTCCTACCATGAGGCCAAATATCCTTCTGAGGAGCTACCGTAATCACAAACCTA
Camarhynchus_parvulus         GGATACGTCCTACCATGAGGCCAAATATCCTTCTGAGGAGCTACCGTAATCACAAACCTA
                              ** *********************************** ******************** 

Certhidea_olivacea            TTCTCAGCCATCCCCTACATTGGACAAACATTGGTCGAATGAGCCTGAGGCGGATTCTCC
Certhidea_fusca               TTCTCAGCCATCCCCTACATTGGACAAACATTGGTCGAATGAGCCTGAGGCGGATTCTCC
Pinaroloxias_inornata         TTCTCAGCCATCCCCTACATTGGACAAACACTAGTCGAATGAGCCTGAGGCGGATTCTCC
Platyspiza_crassirostris      TTCTCAGCCATCCCCTACATTGGACAAACACTAGTCGAATGAGCCTGAGGCGGATTCTCC
Cactospiza_heliobates         TTCTCAGCCATCCCCTACATTGGACAAACACTAGTCGAATGAGCCTGAGGCGGATTCTCC
Camarhynchus_pauper           TTCTCAGCCATCCCCTACATTGGACAAACACTAGTCGAATGAGCCTGAGGTGGATTCCCC
Geospiza_difficilis           TTCTCAGCCATCCCCTACATTGGACAAACACTAGTCGAATGAGCCTGAGGCGGATTCTCC
Geospiza_fuliginosa           TTCTCAGCCATCCCATACATTGGACAAACACTAGTCGAATGAGCCTGAGGCGGATTCTCC
Geospiza_fortis               TTCTCAGCCATCCCCTACATTGGACAAACACTAGTCGAATGAGCCTGAGGCGGATTCTCC
Geospiza_conirostris          TTCTCAGCCATCCCCTACATTGGACAAACACTAGTCGAATGAGCCTGAGGCGGATTCTCC
Geospiza_magnirostris         TTCTCAGCCATCCCCTACATTGGACAAACACTAGTCGAATGAGCCTGAGGCGGATTCTCC
Geospiza_scandens             TTCTCAGCCATCCCCTACATTGGACAAACACTAGTCGAATGAGCCTGAGGCGGATTCTCC
Camarhynchus_psittacula       TTCTCAGCCATCCCCTACATTGGACAAACACTAGTCGAATGAGCCTGAGGCGGATTCTCC
Cactospiza_pallida            TTCTCAGCCATCCCCTACATTGGACAAACACTAGTCGAATGAGCCTGAGGCGGATTCTCC
Camarhynchus_parvulus         TTCTCAGCCATCCCCTACATTGGACAAACACTAGTCGAATGAGCCTGAGGCGGATTCTCC
                              ************** *************** * ***************** ****** **

Certhidea_olivacea            GTCGACAACCCTACCCTCACCCGATTCTTCGCCCTTCACTTCCTCCTCCCATTCGTCATC
Certhidea_fusca               GTCGACAACCCTACCCTCACCCGATTCTTTGCCCTTCACTTCCTCCTCCCATTCGTCATC
Pinaroloxias_inornata         GTCGACAACCCTACCCTCACCCGATTCTTTGCCCTTCACTTCCTACTCCCATTTGTCATC
Platyspiza_crassirostris      GTCGACAACCCTACCCTCACCCGATTCTTTGCCCTTCACTTCCTCCTCCCATTCGTCATC
Cactospiza_heliobates         GTCGACANCCCTACCCTCACCCGATTCTTTGCCCTTCACTTCCTCCTCCCATTCGTCATC
Camarhynchus_pauper           GTCGACAACCCTACCCTCACCCGATCCTTTGCCCTTCACTTCCTCCTCCCATTCGTCATC
Geospiza_difficilis           GTCGAGAACCCTACCCTCACCCGATTCTTTGCCCTTCACTTCCTCCTCCCATTCGTCATC
Geospiza_fuliginosa           GTCGACAACCCTACCCTCACCCGATTCTTTGCCCTTCACTTCCTCCTCCCATTCGTCATC
Geospiza_fortis               GTCGACAACCCTACCCTCACCCGATTCTTTGCCCTTCACTTCCTCCTCCCATTCGTCATC
Geospiza_conirostris          GTCGACAACCCTACCCTCACCCGATTCTTTGCCCTTCACTTCCTCCTCCCATTCGTCATC
Geospiza_magnirostris         GTCGACAACCCTACCCTCACCCGATTCTTTGCCCTTCACTTCCTCCTCCCATTCGTCATC
Geospiza_scandens             GTCGACAACCCTACCCTCACCCGATTCTTTGCCCTTCACTTCCTCCTCCCATTCGTCATC
Camarhynchus_psittacula       GTCGACAACCCTACCCTCACCCGATTCTTTGCCCTTCACTTCCTCCTCCCATTCGTCATC
Cactospiza_pallida            GTCGACAACCCTACCCTCACCCGATTCTTTGCCCTTCACTTCCTCCTCCCATTCGTCATC
Camarhynchus_parvulus         GTCGACAACCCTACCCTCACCCGATTCTTTGCCCTTCACTTCCTCCTCCCATTCGTCATC
                              ***** * ***************** *** ************** ******** ******

Certhidea_olivacea            GTAGGCCTCACACTCGTCCACCTAACCTTCCTGCACGAAACAGGCTCAAACAACCCAATG
Certhidea_fusca               GTAGGCCTCACACTCGTCCACCTAACCTTCCTGCACGAAACAGGCTCAAACAACCCAATG
Pinaroloxias_inornata         GTAGGCCTCACACTCGTCCACCTAACCTTCCTGCACGAAACGGGCTCAAATAACCCAATG
Platyspiza_crassirostris      GTAGGCCTCACGCTTGTCCACCTAACCTTCCTGCACGAAACGGGCTCAAATAACCCAATG
Cactospiza_heliobates         GTAGGCCTCACACTCGTCCACCTAACCTTCCTGCACGAAACGGGCTCAAANAACCCAATG
Camarhynchus_pauper           GTAGGCCTCACACTCGTCCACCTAACCTTCCTACACGAAACGGGCTCAAATAACCCAATG
Geospiza_difficilis           GTAGGCCTCACACTCGTCCACCTAACCTTCCTGCACGAAACGGGCTCAAATAACCCAATG
Geospiza_fuliginosa           GTAGGCCTCACACTCGTCCACCTAACCTTCCTGCACGAAACGGGCTCAAATAACCCAATG
Geospiza_fortis               GTAGGCCTCACACTCGTCCACCTAACCTTCCTGCACGAAACGGGCTCAAATAACCCAATG
Geospiza_conirostris          GTAGGCCTCACACTCGTCCACCTAACCTTCCTGCACGAAACGGGCTCAAATAACCCAATG
Geospiza_magnirostris         GTAGGCCTCACACTCGTCCACCTAACCTTCCTGCACGAAACGGGCTCAAATAACCCAATG
Geospiza_scandens             GTAGGCCTCACACTCGTCCACCTAACCTTCCTGCACGAAACGGGCTCAAATAACCCAATG
Camarhynchus_psittacula       GTAGGCCTCACACTCGTCCACCTAACCTTCCTACACGAAACGGGCTCAAATAACCCAATG
Cactospiza_pallida            GTAGGCCTCACACTCGTCCACCTAACCTTCCTACACGAAACGGGCTCAAATAACCCAATG
Camarhynchus_parvulus         GTAGGCCTCACACTCGTCCACCTAACCTTCCTACACGAAACGGGCTCAAATAACCCAATG
                              *********** ** ***************** ******** ******** *********

Certhidea_olivacea            GGCATCCCCTCAGACTGCGACAAAATCCCCTTCCACCCCTACTACACCATTAAAGACATC
Certhidea_fusca               GGCATCCCCTCAGACTGCGACAAAATCCCCTTCCACCCCTACTACACCATTAAAGACATC
Pinaroloxias_inornata         GGCATCCCCTCAGACTGCGACAAGATCCCCTTCCACCCCTACTACACCATCAAAGACATC
Platyspiza_crassirostris      GGCATCCCCTCAGACTGCGACAAAATCCCCTTCCACCCCTACTACACCATCAAAGACATC
Cactospiza_heliobates         GGCATCCCCTCAGACTGCGACAANATCCCCTTCCACCCCTACTACACCATCAAAGACATC
Camarhynchus_pauper           GGCATCCCCTCAGACTGCGACAAGATCCCCTTCCACCCCTACTACGCCATCAAAGACATC
Geospiza_difficilis           GGCATCCCCTCAGACTGCGACAAGATCCCCTTCCACCCCTACTACACCATCAAAGACATC
Geospiza_fuliginosa           GGCATCCCCTCAGACTGCGACAAGATCCCCTTCCACCCCTACTACACCATCAAAGACATC
Geospiza_fortis               GGCATCCCCTCAGACTGCGACAAGATCCCCTTCCACCCCTACTACACCATCAAAGACATC
Geospiza_conirostris          GGCATCCCCTCAGACTGCGACAAGATCCCCTTCCACCCCTACTACACCATCAAAGACATC
Geospiza_magnirostris         GGCATCCCCTCAGACTGCGACAAGATCCCCTTCCACCCCTACTACACCATCAAAGACATC
Geospiza_scandens             GGCATCCCCTCAGACTGCGACAAGATCCCCTTCCACCCCTACTACACCATCAAAGACATC
Camarhynchus_psittacula       GGCATCCCCTCAGACTGCGACAAGATCCCCTTCCACCCCTACTACACCATCAAAGACATC
Cactospiza_pallida            GGCATCCCCTCAGACTGCGACAAGATCCCCCTCCACCCCTACTACACCATCAAAGACATC
Camarhynchus_parvulus         GGCATCCCCTCAGACTGCGACAAGATCCCCTTCCACCCCTACTACACCATCAAAGACATC
                              *********************** ****** ************** **** *********

Certhidea_olivacea            CCAGGCTTCGTACTAATACTCTCCCTGCTCGTCTCACTAGCCCTATTCTCCCCCAACCTC
Certhidea_fusca               CTAGGCTTCGTACTAATACTCTCCCTGCTCGTCTCACTAGCCCTATTCTCCCCCAACCTC
Pinaroloxias_inornata         TTAGGTTTCGTACTAATACTCTCTCTGCTCGCCTCACTAGCCCTATTCTCTCCTAACCTC
Platyspiza_crassirostris      CTAGGCTTCGTACTAATACTCTCTCTGCTCGCCTCACTAGCCCTATTCTCCCCCAACCTC
Cactospiza_heliobates         TTAGGCTTCGTGCTAATACTCTCTCTGCTCNTCTCACTAGCCCTATTCTCCCCCAACCTC
Camarhynchus_pauper           TTAGGCTTCGTGCTAATACTCTCTCTGCTCGTCTCACTAGCCCTATTCTCCCCCAACCTC
Geospiza_difficilis           CTAGGCTTCGTACTAATACCCTCTCTGCTCGTCTCACTAGCCCTATTCTCCCCCAACCTC
Geospiza_fuliginosa           TTAGGCTTCGTACTAATACTCTCTCTGCTCGTCTCACTAGCCCTATTCTCCCCCAACCTC
Geospiza_fortis               CTAGGCTTCGTACTAATACTCTCTCTGCTCGTCTCACTAGCCCTATTCTCCCCCAACCTC
Geospiza_conirostris          CTAGGCTTCGTACTAATACTCTCTCTGCTCGTCTCACTAGCCCTATTCTCCCCCAACCTC
Geospiza_magnirostris         CTAGGCTTCGTACTAATACTCTCTCTGCTCGTCTCACTAGCCCTATTCTCCCCCAACCTC
Geospiza_scandens             CTAGGCTTCGTACTAATACTCTCTCTGCTCGTCTCACTAGCCCTATTCTCCCCCAACCTC
Camarhynchus_psittacula       TTANGCCTCGTGCTAATACTCTCTCTGCTCGTCTCACTAGCCCTATTCTCCCCCAACCTC
Cactospiza_pallida            TTAGGCTTCGTGCTAATACTCTCTCTGCTCGTCTCACTAGCCCTATTCTCCCCCAACCTC
Camarhynchus_parvulus         TTAGGCTTCGTGCTAATACTCTCTCTGCTCGTCTCACTAGCCCTATTCTCCCCCAACCTC
                                * *  **** ******* *** ******  ****************** ** ******

Certhidea_olivacea            CTAGGCGACCCAGAAAACTTCACGCCAGCCAACCCACTAACCACCCCTCCCCACATTAAA
Certhidea_fusca               CTAGGCGACCCAGAAAACTTCACGCCAGCCAACCCACTAACCACCCCTCCCCACATTAAA
Pinaroloxias_inornata         CTAGGCGACCCAGAAAACTTCACACCAGCCAACCCGCTAACCACCCCTCCCCACATCAAA
Platyspiza_crassirostris      CTAGGCGACCCAGAAAACTTCACACCAGCCAACCCACTAACCACCCCTCCCCACATCAAA
Cactospiza_heliobates         CTAGGCGACCCAGAAAACTTCACACCAGCCAATCCACTAACCACCCCTCCCCACATCAAA
Camarhynchus_pauper           CTAGGCGACCCAGAAAACTTCACACCAGCGAATCCACTAACCACCCCTCCCCACATCAAA
Geospiza_difficilis           CTAGGCGACCCAGAAAACTTCACACCAGCCAATCCACTAACCACCCCTCCCCACATCAAA
Geospiza_fuliginosa           CTAGGCGACCCAGAAAACTTCACGCCAGCCAATCCACTAACCACCCCTCCCCATATCAAA
Geospiza_fortis               CTAGGCGACCCAGAAAACTTCACACCAGCCAATCCACTAACCACCCCTCCCCACATCAAA
Geospiza_conirostris          CTAGGCGACCCAGAAAACTTCACACCAGCCAATCCACTAACCACCCCTCCCCACATCAAA
Geospiza_magnirostris         CTAGGCGACCCAGAAAACTTCACACCAGCCAACCCACTAACCACCCCTCCCCACATCAAA
Geospiza_scandens             CTAGGCGACCCAGAAAACTTCACACCAGCCAACCCACTAACCACCCCTCCCCACATCAAA
Camarhynchus_psittacula       CTAGGCGACCCAGAAAACTTCACACCAGCCAATCCACTAACCACCCCTCCCCACATCAAA
Cactospiza_pallida            CTAGGCGACCCAGAAAACTTCACACCAGCCAATCCACTAACCACCCCTCCCCACATCAAA
Camarhynchus_parvulus         CTAGGCGACCCAGAAAACTTCACACCAGCCAATCCACTAACCACCCCTCCCCACATCAAA
                              *********************** ***** ** ** ***************** ** ***

Certhidea_olivacea            CCCGAATGATACTTCCTCTTCGCCTACGCCATCCTTCGATCCATCCCAAACAAACTAGGA
Certhidea_fusca               CCCGAATGATACTTCCTCTTCGCCTACGCCATCCTTCGATCCATCCCAAACAAACTAGGA
Pinaroloxias_inornata         CCTGAATGATACTTCCCATTTGCCTACGCCATCCTTCGATCCATCCCAAACAAACTAGGA
Platyspiza_crassirostris      CCCGAATGATACTTCCTATTCGCCTACGCCATCCTTCGATCCATCCCAAACAAACTAGGA
Cactospiza_heliobates         CCTGAATGATACTTCCTATTCGCCTACGCCATCCTTCGATCCATCCCAAACAAACTAGGA
Camarhynchus_pauper           CCTGAATGATACTTCCTATTCGCCTACGCCATCCTTCGATCCATCCCAAACAAACTAGGA
Geospiza_difficilis           CCTGAATGATACTTCCTATTCGCCTACGCCATCCTTCGATCCATCCCAAACAAACTAGGA
Geospiza_fuliginosa           CCTGAATGATACTTCCTATTCGCCTACGCCATCCTTCGATCCATCCCAAACAAACTAGGA
Geospiza_fortis               CCTGAATGATACTTCCTATTCGCCTACGCCATCCTTCGATCCATCCCAAACAAACTAGGA
Geospiza_conirostris          CCTGAATGATACTTCCTATTCGCCTACGCCATCCTTCGATCCATCCCAAACAAACTAGGA
Geospiza_magnirostris         CCTGAATGATACTTCCTATTCGCCTACGCCATCCTTCGATCCATCCCAAACAAACTAGGA
Geospiza_scandens             CCTGAATGATACTTCCTATTCGCCTACGCCATCCTTCGATCCATCCCAAACAAACTAGGA
Camarhynchus_psittacula       CCTGAATGATACTTCCTATTCGCCTACGCCATCCTTCGATCCATCCCAAACAAACTAGGA
Cactospiza_pallida            CCTGAGTGATACTTCCTATTCGCCTACGCCATCCTTCGATCCATCCCAAACAAACTAGGA
Camarhynchus_parvulus         CCTGAATGATACTTCCTATTCGCCTACGCCATCCTTCGATCCATCCCAAACAAACTAGGA
                              ** ** **********  ** ***************************************

Certhidea_olivacea            GGAGTACTAGCCCTAGCCGCCTCAATCCTAGTCCTATTCCTCATGCCACTACTCCACACA
Certhidea_fusca               GGAGTACTAGCCCTAGCCGCCTCAATCCTAGTCCTATTCCTCATGCCACTACTCCACACA
Pinaroloxias_inornata         GGAGTACTAGCCCTAGCCGCCTCAATCCTAGTCCTATTCCTCATGCCACTACTTCACACA
Platyspiza_crassirostris      GGAGTACTAGCCCTAGCCGCCTCAACCCTAGTCCTATTCCTCATGCCACTACTTCACACA
Cactospiza_heliobates         GGAGTACTAGCCCTAGCCGCCTCAATCCTAGTCCTNTTCCTTATGCCACTACTTCACACA
Camarhynchus_pauper           GGAGTACTAGCCCTAGCCGCCTCAATCCTAGTCCTATTCCTCATGCCACTACTTCACACA
Geospiza_difficilis           GGAGTACTAGCCCTAGCGCCTTCAATCCTAGTCCTATTCCTCATGCCACTACTTCACACA
Geospiza_fuliginosa           GGAGTACTAGCCCTAGCCGCCTCAATCCTAGTCCTATTCCTCATGCCACTACTTCACACA
Geospiza_fortis               GGAGTACTAGCCCTAGCCGCCTCAATCCTAGTCCTATTCCTCATGCCACTACTTCACACA
Geospiza_conirostris          GGAGTACTAGCCCTAGCCGCCTCAATCCTAGTCCTATTCCTCATGCCACTACTTCACACA
Geospiza_magnirostris         GGAGTACTAGCCCTAGCCGCCTCAATCCTAGTCCTATTCCTCATGCCACTACTTCACACA
Geospiza_scandens             GGAGTACTAGCCCTAGCCGCCTCAATCCTAGTCCTATTCCTCATGCCACTACTTCACACA
Camarhynchus_psittacula       GGAGTACTAGCCCTAGCCGCCTCAATCCTAGTCCTATTCCTCATGCCACTACTTCACACA
Cactospiza_pallida            GGAGTACTGGCCCTAGCCGCCTCAATCCTAGTCCTATTCCTCATGCCACTACTTCACACA
Camarhynchus_parvulus         GGAGTACTAGCCCTAGCCGCCTCAATCCTAGTCCTATTCCTCATGCCACTACTTCACACA
                              ******** ********  * **** ********* ***** *********** ******

Certhidea_olivacea            TCCAAACTACGATCAATAACATTCCGCCCCCTATCACAAATCCTATTCTGAGCCCTAGTC
Certhidea_fusca               TCCAAACTACGATCAATAACATTCCGCCCCCTATCACAAATCCTATTCTGAGCCCTAGTC
Pinaroloxias_inornata         TCCAAACTACGATCAATAACATTCCGCCCCCTATCACAAATCCTATTCTGAGCCCTAGTC
Platyspiza_crassirostris      TCCAAACTACGATCAATAACATTCCGCCCCCTATCACAAATCCTATTCTGAGCACTAGTC
Cactospiza_heliobates         TNCAAACTACGATCAATAACATTNCGCCCCCTATCACAAATCCTATTCTGAGCCCTA---
Camarhynchus_pauper           TCCAAACTACGATCAATAACATTCCGCCCCCTATCACAAATCCTATTCTGAGCCCTAGTC
Geospiza_difficilis           TCCAAACTACGATCAATAACATTCCGCCCCCTATCACAAATCCTATTCTGAGCCCTAGTC
Geospiza_fuliginosa           TCCAAACTACGATCAATAACATTCCGCCCCCTATCACAAATCCTATTCTGAGCCCTAGTC
Geospiza_fortis               TCCAAACTACGATCAATAACATTCCGCCCCCTATCACAAATCCTATTCTGAGCCCTAGTC
Geospiza_conirostris          TCCAAACTACGATCAATAACATTCCGCCCCCTATCACAAATCCTATTCTGAGCCCTAGTC
Geospiza_magnirostris         TCCAAACTACGATCAATAACATTCCGCCCCCTATCACAAATCCTATTCTGAGCCCTAGTC
Geospiza_scandens             TCCAAACTACGATCAATAACATTCCGCCCCCTATCACAAATCCTATTCTGAGCCCTAGTC
Camarhynchus_psittacula       TCCAAACTACGATCAATAACATTCNGCNNCCTATCACAAATCCTATTCTGAGCCCTAGTC
Cactospiza_pallida            TCCAAACTACGATCAATAACATTCCGCCCCCTATCACAAATCCTATTCTGAGCCCTAGTC
Camarhynchus_parvulus         TCCAAACTACGATCAATAACATTCCGCCCCCTGTCACAAATCCTATTCTGAGCCCTAGTC
                              * *********************  **  *** ******************** ***   

Certhidea_olivacea            ACCAACGTTCTCATCCTAACCTGAGTAGGAAGC
Certhidea_fusca               ACCAACGTCCTCATCCTAACCTGAGA-------
Pinaroloxias_inornata         ACCAACGTCCTCATCCTAACCTGAGTAGGAAGC
Platyspiza_crassirostris      ACCAACGTCCTCATCCTGACCTGAGTAGGAAGC
Cactospiza_heliobates         ---------------------------------
Camarhynchus_pauper           ACCAACGTCCTCATCCTAACCTGAGTAGGAAGC
Geospiza_difficilis           ACCAACGTCCTCATCCTAACCTGAGTAGGAAGC
Geospiza_fuliginosa           ACCAACGTCCTCATCCTAACCTGAGTAGGAAGC
Geospiza_fortis               ACCAACGTCCTCATCCTAACCTGAGTAGGAAGC
Geospiza_conirostris          ACCAACGTCCTCATCCTAACCTGAGTAGGAAGC
Geospiza_magnirostris         GCCAACGTCCTCATCCTAACCTGAGTAGGAAGC
Geospiza_scandens             ACCAACGTCCTCATCCTAACCTGAGTAGGGAGC
Camarhynchus_psittacula       ACCAACGTCCTCATCCTAACCTGAGTAGGAAGC
Cactospiza_pallida            ACCAACGTCCTCATCCTAACCTGAGTAGGAAGC
Camarhynchus_parvulus         ACCAACGTCCTCATCCTAACCTGAGTAGGAAGC
                                                               
